In [349]:
#A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, 
#or a table with rows and columns
import pandas as pd
import numpy as np

#APPROACH 1 - LIST
data=[[420,50],[320,40],[480,60],[230,34],[560,78],[120,12],[490,55],[690,67]]
colNames=['Calories','Duration']

df=pd.DataFrame(data=data,columns=colNames)
df

   Calories  Duration
0       420        50
1       320        40
2       480        60
3       230        34
4       560        78
5       120        12
6       490        55
7       690        67

In [348]:
#APPROACH 2 - NUMPY ARRAY
data_np=np.array([
    [420,50],[320,40],[480,60],[230,34],[560,34],[120,12],[490,55],[690,67]
])
colNames=['Calories','Duration']

df=pd.DataFrame(data=data_np,columns=colNames)
df

   Calories  Duration
0       420        50
1       320        40
2       480        60
3       230        34
4       560        34
5       120        12
6       490        55
7       690        67

In [350]:
#APPROACH 3 - USING PYTHON DICTIONARY 
data = {
  "Calories": [420, 380, 390],
  "Duration": [50, 40, 45]
}

#load data into a DataFrame object:
dictf = pd.DataFrame(data)
dictf

   Calories  Duration
0       420        50
1       380        40
2       390        45

In [351]:
# ALL THESE APPROACHES HAVE LIMITATIONS AS WE ARE MANUALLY PUTTING OUR DATA IN THEM , 
# IT WILL NOT HELP WHEN DATASET IS LARGE

In [352]:
# A simple way to store big data set is to use CSV file

In [353]:
#Checking column data type using 'dtype' attributes
df.dtypes
#gives data type

Calories    int64
Duration    int64
dtype: object

In [354]:
df.head()  #Selects top N number of records (default is 5)

   Calories  Duration
0       420        50
1       320        40
2       480        60
3       230        34
4       560        78

In [355]:
df.tail() #Selects bottom N number of records (default is 5)

   Calories  Duration
3       230        34
4       560        78
5       120        12
6       490        55
7       690        67

In [356]:
df.shape  #used to get no of rows and columns in data set

(8, 2)

In [357]:
df.info()#this method gives column data type + no of non null values in data set

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Calories  8 non-null      int64
 1   Duration  8 non-null      int64
dtypes: int64(2)
memory usage: 256.0 bytes

# **Slicing**
**Selecting columns and performing slicing operations in pandas**

In [358]:
#Select columns using brackets :

#Selecting one column using double brackets 
df[['Duration']].head()

   Duration
0        50
1        40
2        60
3        34
4        78

In [359]:
df[['Duration']].tail()

   Duration
3        34
4        78
5        12
6        55
7        67

In [360]:
#Selecting multiple columns using double brackets

df[['Calories','Duration']].head()

   Calories  Duration
0       420        50
1       320        40
2       480        60
3       230        34
4       560        78

In [361]:
#This is pandas dataframe 
type(df[['Calories','Duration']].head())

pandas.core.frame.DataFrame

In [362]:
#Selecting one column using single brackets 
df['Duration'].head()

#Gives in output pandas series which is one dimensional array which can be labelled

0    50
1    40
2    60
3    34
4    78
Name: Duration, dtype: int64

In [363]:
#We cannot select multiple columns by using single brackets 
#df['Duration','Calories']

#The above will throw a key error

# **Pandas Slicing**
With a pandas series (1D) , we can select rows using slicing like this :-
series [start_index:end_index)

The end index is not inclusive

In [364]:
df['Calories']

0    420
1    320
2    480
3    230
4    560
5    120
6    490
7    690
Name: Calories, dtype: int64

In [365]:
df['Calories'][0:4]

0    420
1    320
2    480
3    230
Name: Calories, dtype: int64

# **Selecting Columns Using loc**
The pandas attribute .loc allows you to select columns ,index ,and slice your data

In [366]:
df.loc[:,['Duration']].head()
#Starts from zero

   Duration
0        50
1        40
2        60
3        34
4        78

In [367]:
df.loc[3:,['Duration']].head()
#Starts from third

   Duration
3        34
4        78
5        12
6        55
7        67

In [368]:
df.loc[1:6,['Duration']].head()
#From 1 to 6

#.loc[start:end,[column name ]].head/tail

   Duration
1        40
2        60
3        34
4        78
5        12

In [323]:
from google.colab import files
 
 
uploaded = files.upload()

Saving FYBtech CS_1.csv to FYBtech CS_1 (4).csv

In [324]:
cs=pd.read_csv('FYBtech CS_1.csv')
cs

,MIS No,Student Name,Division,Batches,Branch,Coep MailId,Mob No,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,112103001.0,AARYA ROHIT KAWALAY,Div-9,A9,Computer Engineering,aaryark21.comp@coep.ac.in,9.623451e+09,NaN,NaN,NaN,NaN
1,112103002.0,AAYUSH SHRIKANT ATHAWALE,Div-8,A8,Computer Engineering,aayushsa21.comp@coep.ac.in,9.307100e+09,NaN,NaN,NaN,NaN
2,112103003.0,ABHANG ANUJ PRAVIN,Div-9,A9,Computer Engineering,abhangap21.comp@coep.ac.in,9.769518e+09,NaN,NaN,NaN,NaN
3,112103004.0,ABHINAV KURULE,Div-8,A8,Computer Engineering,abhinavk21.comp@coep.ac.in,8.451956e+09,NaN,NaN,NaN,NaN
4,112103005.0,AGARWAL RISHABH RAVI,Div-10,A10,Computer Engineering,agarwalrr21.comp@coep.ac.in,7.738780e+09,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
641,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [325]:
cs.head()

,MIS No,Student Name,Division,Batches,Branch,Coep MailId,Mob No,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,112103001.0,AARYA ROHIT KAWALAY,Div-9,A9,Computer Engineering,aaryark21.comp@coep.ac.in,9.623451e+09,NaN,NaN,NaN,NaN
1,112103002.0,AAYUSH SHRIKANT ATHAWALE,Div-8,A8,Computer Engineering,aayushsa21.comp@coep.ac.in,9.307100e+09,NaN,NaN,NaN,NaN
2,112103003.0,ABHANG ANUJ PRAVIN,Div-9,A9,Computer Engineering,abhangap21.comp@coep.ac.in,9.769518e+09,NaN,NaN,NaN,NaN
3,112103004.0,ABHINAV KURULE,Div-8,A8,Computer Engineering,abhinavk21.comp@coep.ac.in,8.451956e+09,NaN,NaN,NaN,NaN
4,112103005.0,AGARWAL RISHABH RAVI,Div-10,A10,Computer Engineering,agarwalrr21.comp@coep.ac.in,7.738780e+09,NaN,NaN,NaN,NaN

In [326]:
cs.tail()

,MIS No,Student Name,Division,Batches,Branch,Coep MailId,Mob No,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
641,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [327]:
cs['MIS No']

0      112103001.0
1      112103002.0
2      112103003.0
3      112103004.0
4      112103005.0
          ...
638            NaN
639            NaN
640            NaN
641            NaN
642            NaN
Name: MIS No, Length: 643, dtype: float64

In [328]:
cs.shape

(643, 11)

In [329]:
cs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643 entries, 0 to 642
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MIS No         160 non-null    float64
 1   Student Name   160 non-null    object
 2   Division       160 non-null    object
 3   Batches        160 non-null    object
 4   Branch         160 non-null    object
 5   Coep MailId    160 non-null    object
 6   Mob No         160 non-null    float64
 7   Unnamed: 7     0 non-null      float64
 8   Unnamed: 8     0 non-null      float64
 9   Unnamed: 9     0 non-null      float64
 10  Unnamed: 10    0 non-null      float64
dtypes: float64(6), object(5)
memory usage: 55.4+ KB

# **Filtering Data**

In [330]:
cs['Mob No'][30:35]

30    7.773960e+09
31    9.130435e+09
32    9.823279e+09
33    7.447767e+09
34    9.922067e+09
Name: Mob No, dtype: float64

In [331]:
cs.dtypes

MIS No           float64
Student Name      object
Division          object
Batches           object
Branch            object
Coep MailId       object
Mob No           float64
Unnamed: 7       float64
Unnamed: 8       float64
Unnamed: 9       float64
Unnamed: 10      float64
dtype: object

In [332]:
cs['Division'].value_counts()

Div-9     32
Div-8     32
Div-10    32
Div-6     32
Div-7     32
Name: Division, dtype: int64

In [333]:
cs['Batches'].value_counts()

A9     18
A10    18
A6     18
A8     17
A7     17
B8     15
B7     15
B9     14
B10    14
B6     14
Name: Batches, dtype: int64

In [334]:
cs['Mob No']==7447766663

0      False
1      False
2      False
3      False
4      False
       ...
638    False
639    False
640    False
641    False
642    False
Name: Mob No, Length: 643, dtype: bool

# **Renaming & deleting Columns**
Changing column names or removing unnecessary columns

In [335]:
#Rename Columns - 1) Dictionary substitution  2) List replacement
df.head()
#dataframe before renaming columns

   Calories  Duration
0       420        50
1       320        40
2       480        60
3       230        34
4       560        78

In [336]:
# Approach 1 - Dictionary Substitution using rename method
df=df.rename(columns={'Calories':'Calories_Burnt','Duration':'Time taken'})

In [337]:
#dataframe after renaming
df

   Calories_Burnt  Time taken
0             420          50
1             320          40
2             480          60
3             230          34
4             560          78
5             120          12
6             490          55
7             690          67

In [338]:
#Approach 2 - List replacement 
df.columns=['Calories','Duration']
df

   Calories  Duration
0       420        50
1       320        40
2       480        60
3       230        34
4       560        78
5       120        12
6       490        55
7       690        67

In [339]:
#Deleting columns 
#Approach 1 - This allows us to drop multiple columns at a time

#df=df.drop(columns=['Duration'])

In [340]:
df

   Calories  Duration
0       420        50
1       320        40
2       480        60
3       230        34
4       560        78
5       120        12
6       490        55
7       690        67

In [341]:
#Approach 2 - Use the del command 

#del df['Duration']

# **Aggregate Functions**

In [342]:
#Sum the values in the column 
df['Duration'].sum()

396

In [343]:
#Sum all the values across all columns 
df.sum()

Calories    3310
Duration     396
dtype: int64

In [344]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Calories  8 non-null      int64
 1   Duration  8 non-null      int64
dtypes: int64(2)
memory usage: 256.0 bytes

# **Identifying missing Data**
Values will be originally missing from pandas dataset.
Missing values are called NaN or None

In [345]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Calories  8 non-null      int64
 1   Duration  8 non-null      int64
dtypes: int64(2)
memory usage: 256.0 bytes

In [346]:
df['Duration'].isna().head()
#Output is Pandas series with True/false answer

0    False
1    False
2    False
3    False
4    False
Name: Duration, dtype: bool

# **Removing or Filling Missing Data**
This is an imp subject before you graph data .You should make sure you are not trying to graph some missing values as that can cause an error or misinterpretation of the data

In [347]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Calories  8 non-null      int64
 1   Duration  8 non-null      int64
dtypes: int64(2)
memory usage: 256.0 bytes

In [369]:
cs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643 entries, 0 to 642
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MIS No         160 non-null    float64
 1   Student Name   160 non-null    object
 2   Division       160 non-null    object
 3   Batches        160 non-null    object
 4   Branch         160 non-null    object
 5   Coep MailId    160 non-null    object
 6   Mob No         160 non-null    float64
 7   Unnamed: 7     0 non-null      float64
 8   Unnamed: 8     0 non-null      float64
 9   Unnamed: 9     0 non-null      float64
 10  Unnamed: 10    0 non-null      float64
dtypes: float64(6), object(5)
memory usage: 55.4+ KB

In [375]:
newData={
    "Student Roll ":[1,2,3,4,5,6,7,8,9,10],
    "Attendence":[11,12,13,14,np.nan,16,17,18,19,20]
}

nd=pd.DataFrame(newData)
nd
#Above we will discuss multiple ways for filling NaN values

   Student Roll   Attendence
0              1        11.0
1              2        12.0
2              3        13.0
3              4        14.0
4              5         NaN
5              6        16.0
6              7        17.0
7              8        18.0
8              9        19.0
9             10        20.0

In [376]:
#1)Filling NaN with zero is probably a bad idea

#nd['Attendence'][1:10].fillna(0)

#Zero misinterprets the data

1    12.0
2    13.0
3    14.0
4     0.0
5    16.0
6    17.0
7    18.0
8    19.0
9    20.0
Name: Attendence, dtype: float64

In [377]:
#2) Back fill in value
nd['Attendence'][1:10].fillna(method="bfill")

1    12.0
2    13.0
3    14.0
4    16.0
5    16.0
6    17.0
7    18.0
8    19.0
9    20.0
Name: Attendence, dtype: float64

In [379]:
#3) Forward fill in value
nd['Attendence'][1:10].fillna(method="ffill")

1    12.0
2    13.0
3    14.0
4    14.0
5    16.0
6    17.0
7    18.0
8    19.0
9    20.0
Name: Attendence, dtype: float64

In [381]:
#4) Linear interpolation
nd['Attendence'][1:10].interpolate(method="linear")
#Uses linear model to fill in with missing value

1    12.0
2    13.0
3    14.0
4    15.0
5    16.0
6    17.0
7    18.0
8    19.0
9    20.0
Name: Attendence, dtype: float64

In [382]:
nd

   Student Roll   Attendence
0              1        11.0
1              2        12.0
2              3        13.0
3              4        14.0
4              5         NaN
5              6        16.0
6              7        17.0
7              8        18.0
8              9        19.0
9             10        20.0

In [386]:
#Pandas to numpy array conversion

#Approach 1
df.to_numpy()

array([[420,  50],
       [320,  40],
       [480,  60],
       [230,  34],
       [560,  78],
       [120,  12],
       [490,  55],
       [690,  67]])

In [388]:
#Approach 2 
df.values

array([[420,  50],
       [320,  40],
       [480,  60],
       [230,  34],
       [560,  78],
       [120,  12],
       [490,  55],
       [690,  67]])

In [390]:
#Conversion of Pandas dataframe to dictionaries
df.to_dict()

{'Calories': {0: 420, 1: 320, 2: 480, 3: 230, 4: 560, 5: 120, 6: 490, 7: 690},
 'Duration': {0: 50, 1: 40, 2: 60, 3: 34, 4: 78, 5: 12, 6: 55, 7: 67}}